//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: hello.proto

package grpc_code_gen.hello;

@kotlin.jvm.JvmName("-initializehelloReply")
public inline fun helloReply(block: grpc_code_gen.hello.HelloReplyKt.Dsl.() -> kotlin.Unit): grpc_code_gen.hello.Hello.HelloReply =
  grpc_code_gen.hello.HelloReplyKt.Dsl._create(grpc_code_gen.hello.Hello.HelloReply.newBuilder()).apply { block() }._build()
public object HelloReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc_code_gen.hello.Hello.HelloReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc_code_gen.hello.Hello.HelloReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc_code_gen.hello.Hello.HelloReply = _builder.build()

    /**
     * <code>string message = 1;</code>
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 1;</code>
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc_code_gen.hello.Hello.HelloReply.copy(block: grpc_code_gen.hello.HelloReplyKt.Dsl.() -> kotlin.Unit): grpc_code_gen.hello.Hello.HelloReply =
  grpc_code_gen.hello.HelloReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

